import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavMenu } from "@/components/layout/navbar";
import Provider from "./Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        <Provider>
          <div className="container mx-auto px-4 mt-6">
            <NavMenu />
            <div className="max-w-screen-lg">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
